### ISSUE TITLE
Notes field has no visible border in request review page

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/approvals#1084] opened 2024-03-06 20:25 UTC
### Expected behavior
When reviewing a request I should see a text box for the notes

### Actual behavior
The notes text box is not visible until I click it

**Comment by christinach** [comment] 2024-03-06 20:57
duplicate of https://github.com/pulibrary/approvals/issues/1085

**Closed by christinach** 2024-03-06 20:57 UTC
