### ISSUE TITLE
Supervisor wants to compare travel requests for the same event

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#88] opened 2019-04-29 17:03 UTC
As a supervisor I want to be able to pull up a list of travel requests for the same event and be able to easily compare requests by dates and cost.

**Comment by sdellis** [comment] 2019-05-02 14:28
Related to #39

**Comment by carolyncole** [comment] 2019-05-30 18:15
Duplicate of #55

**Closed by carolyncole** 2019-05-30 18:15 UTC
Labels: Travel, user story
