### ISSUE TITLE
[lux-styleguidist] Missing Content Test Failures

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#1096] opened 2024-03-13 13:51 UTC
In spec/features/new_travel_request_spec.rb

```
Failure/Error: expect(page).to have_content "Super Event's Are Us 2019, A Place To Be (10/01/2019 to 10/03/2019)"
  expected to find text "Super Event's Are Us 2019, A Place To Be (10/01/2019 to 10/03/2019)" in "Absence and Travel Requests\nRequests\nuid1864\nNew Travel Request\nPlease make sure your request complies with the official Princeton University Library Travel Policy before submitting this form.\nEvent Name\nEvent Format\nIn-person\nVirtual\nEvent Dates\nTravel Dates\nLocation\nParticipation\nCommittee chair\nCommittee member\nDonor visit\nMember\nOther\nParticipant\nPresenter\nSite visit\nTraining\nVendor visit\nPurpose\nSpecify the reason this trip is necessary for your job\nNotes to Approvers (optional)\nAdditional information that would help the approver understand the details of the trip (request for time off, desire to stay additional nights, etc.)\nAnticipated Expenses\nDelete\nExpense Type\nOccurrences\nCost per Occurrence\nNote\nTotal\nExpense Type\nAirfare\nCar rental\nGround transportation\nLodging (per night)\nMeals and related expenses (daily)\nMileage - personal car\nMiscellaneous\nOther transit\nParking\nRegistration fee\nTaxi\nTrain\nOccurrences\nCost per Occurrence\nNote\nTotal\nExpense Type\nAirfare\nCar rental\nGround transportation\nLodging (per night)\nMeals and related expenses (daily)\nMileage - personal car\nMiscellaneous\nOther transit\nParking\nRegistration fee\nTaxi\nTrain\nOccurrences\nCost per Occurrence\nNote\nTotal\nAdd Expense\nTotal:\n$130.00\nThis request will be submitted to: Doe1833, Pat1814 (uid1867)\nSubmit Request"
./spec/features/new_travel_request_spec.rb:70:in `block (2 levels) in <top (required)>'````

```Failure/Error: expect(page).to have_content "Possible Date Detected"
  expected to find text "Possible Date Detected" in "Absence and Travel Requests\nRequests\nuid1872\nNew Travel Request\nPlease make sure your request complies with the official Princeton University Library Travel Policy before submitting this form.\nEvent Name\nIt looks like you have a date in this field. Please remove.\nEvent Format\nIn-person\nVirtual\nEvent Dates\nTravel Dates\nLocation\nParticipation\nCommittee chair\nCommittee member\nDonor visit\nMember\nOther\nParticipant\nPresenter\nSite visit\nTraining\nVendor visit\nPurpose\nSpecify the reason this trip is necessary for your job\nNotes to Approvers (optional)\nAdditional information that would help the approver understand the details of the trip (request for time off, desire to stay additional nights, etc.)\nAnticipated Expenses\nDelete\nExpense Type\nOccurrences\nCost per Occurrence\nNote\nTotal\nExpense Type\nAirfare\nCar rental\nGround transportation\nLodging (per night)\nMeals and related expenses (daily)\nMileage - personal car\nMiscellaneous\nOther transit\nParking\nRegistration fee\nTaxi\nTrain\nOccurrences\nCost per Occurrence\nNote\nTotal\nAdd Expense\nTotal:\n$40.00\nThis request will be submitted to: Doe1839, Pat1820 (uid1875)\nSubmit Request"
./spec/features/new_travel_request_spec.rb:131:in `block (2 levels) in <top (required)>'```

**Comment by sandbergja** [comment] 2024-03-15 15:55
This is caused by #1105 -- the form doesn't submit due to an empty date range, so we never see the expected content.  Closing in favor of #1105

**Closed by sandbergja** 2024-03-15 15:55 UTC
Labels: maintenance
