### ISSUE TITLE
[lux-styleguidist] Failure/Error: assert_select "card-header", text:

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/approvals#1098] opened 2024-03-13 13:56 UTC
In spec/views/delegates/index.html.erb_spec.rb and spec/views/delegates/to_assume.html.erb_spec.rb

```Failure/Error: assert_select "card-header", text: /^#{delegate1.delegator}*/, count: 1

Minitest::Assertion:
  Expected exactly 1 element matching "card-header", found 0.
  Expected: 1
    Actual: 0
./spec/views/delegates/to_assume.html.erb_spec.rb:13:in `block (2 levels) in <top (required)>'```

**Comment by maxkadel** [comment] 2024-03-15 13:35
Duplicate of #1099

**Closed by maxkadel** 2024-03-15 13:35 UTC
Labels: maintenance
