### ISSUE TITLE
Absence report form is not styled correctly

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/approvals#1117] opened 2024-03-19 18:27 UTC
### Expected behavior
The form should be neatly styled and fields should be clearly visible

### Actual behavior
![Screenshot 2024-03-19 at 2 24 26 PM](https://github.com/pulibrary/approvals/assets/11181947/f4481b6a-8176-4fd1-b18f-d5d979305873)

The borders on the fields are either not filling the element or there is not a visible border around the form fields

**Comment by christinach** [comment] 2024-03-19 18:31
related to https://github.com/pulibrary/approvals/issues/1090

**Comment by christinach** [comment] 2024-03-19 19:06
duplicate of #1090

**Closed by christinach** 2024-03-19 19:06 UTC
